FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

# FROM nginx
# COPY ./default.conf /etc/nginx/conf.d/default.conf

# FROM builder
CMD ["npm", "run", "dev"]